spring.application.name=SolaceAtelier-Inventory-System

# Database Settings
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:file:./data/inventorydb
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# THE FIX: Wait for tables to be created before running data.sql
spring.jpa.defer-datasource-initialization=true

# Logging
spring.jpa.show-sql=true
spring.sql.init.mode=always

# H2 console path
spring.h2.console.path=/h2-console